export const products = [
  {
    id: "product1",
    name: "Samosa",
    stock: true,
    price: { half: null, full: 10 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Samosa.....",
    quantity: 1,
  },
  {
    id: "product2",
    name: "Bread Pakoda",
    stock: true,
    price: { half: null, full: 15 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Bread.....",
    quantity: 1,
  },
  {
    id: "product3",
    name: "Bread Roll",
    stock: true,
    price: { half: null, full: 10 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Cream.....",
    quantity: 1,
  },
  {
    id: "product4",
    name: "Cream Roll",
    stock: true,
    price: { half: null, full: 15 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Cream.....",
    quantity: 1,
  },
  {
    id: "product5",
    name: "Sandwitch",
    stock: true,
    price: { half: null, full: 25 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Sandwitch.....",
    quantity: 1,
  },
  {
    id: "product6",
    name: "Veg Burger",
    stock: true,
    price: { half: null, full: 30 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Veg Burger.....",
    quantity: 1,
  },
  {
    id: "product7",
    name: "Veg Patty",
    stock: true,
    price: { half: null, full: 15 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Veg Patty.....",
    quantity: 1,
  },
  {
    id: "product8",
    name: "Veg cutlet",
    stock: true,
    price: { half: null, full: 10 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Veg cutlet.....",
    quantity: 1,
  },
  {
    id: "product9",
    name: "Butter Slice",
    stock: true,
    price: { half: null, full: 20 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Butter Slice....",
    quantity: 2,
  },
  {
    id: "product10",
    name: "Double Egg Omellatee with two slice",
    stock: true,
    price: { half: null, full: 40 },
    allergenAlert: "Egg allergy",
    category: "snack",
    url: "http://Egg.....",
    quantity: 1,
  },
  {
    id: "product11",
    name: "Spring Roll",
    stock: true,
    price: { half: null, full: 60 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Spring roll.....",
    quantity: 1,
  },
  {
    id: "product12",
    name: "Momos",
    stock: true,
    price: { half: 30, full: 60 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Momos.....",
    quantity: 1,
  },
  {
    id: "product13",
    name: "Macroni",
    stock: true,
    price: { half: 30, full: 60 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Macroni.....",
    quantity: 1,
  },
  {
    id: "product14",
    name: "Pasta",
    stock: true,
    price: { half: 30, full: 60 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Pasta.....",
    quantity: 1,
  },
  {
    id: "product15",
    name: "Chilly Patatoes",
    stock: true,
    price: { half: 30, full: 60 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Chilly patatoes.....",
    quantity: 1,
  },
  {
    id: "product16",
    name: "Poha",
    stock: true,
    price: { half: null, full: 30 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Poha.....",
    quantity: 1,
  },
  {
    id: "product17",
    name: "Vegetable Spring Roll",
    stock: true,
    price: { half: null, full: 50 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Vegetable Spring Roll.....",
    quantity: 1,
  },
  {
    id: "product18",
    name: "Pav Bhaji",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "wheat allergy",
    category: "snack",
    url: "http://Pav Bhaji.....",
    quantity: 1,
  },
  {
    id: "product19",
    name: "Tea",
    stock: true,
    price: { half: null, full: 10 },
    allergenAlert: "Milk allergy",
    category: "drink",
    url: "http://Tea.....",
    quantity: 1,
  },
  {
    id: "product20",
    name: "Coffee",
    stock: true,
    price: { half: null, full: 15 },
    allergenAlert: "Milk allergy",
    category: "drink",
    url: "http://Coffee.....",
    quantity: 1,
  },
  {
    id: "product21",
    name: "Cold Drink",
    stock: true,
    price: { half: null, full: null },
    allergenAlert: "Caffine allergy",
    category: "drink",
    url: "http://Cold Drink.....",
    quantity: 1,
  },
  {
    id: "product22",
    name: "Subzi",
    stock: true,
    price: { half: null, full: 20 },
    allergenAlert: "Vegetable allergy",
    category: "meal",
    url: "http://Subzi.....",
    quantity: 1,
  },
  {
    id: "product23",
    name: "Allu Bonda",
    stock: true,
    price: { half: null, full: 10 },
    allergenAlert: "Potatoes allergy",
    category: "snack",
    url: "http://Allu Bonda.....",
    quantity: 1,
  },
  {
    id: "product24",
    name: "Honey Chilly Potatoes",
    stock: true,
    price: { half: 35, full: 70 },
    allergenAlert: "Potatoes allergy",
    category: "snack",
    url: "http://Honey Chilly Potatoes.....",
    quantity: 1,
  },
  {
    id: "product25",
    name: "Chhole Rice (with Subji, Salad)",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Chhole Rice.....",
    quantity: 1,
  },
  {
    id: "product26",
    name: "Rajma Rice",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product27",
    name: "Dal Rice",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product28",
    name: "chhole Rice",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product29",
    name: "Rajma Rice (with Subji)",
    stock: true,
    price: { half: null, full: 40 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product30",
    name: "Puri Subzi",
    stock: true,
    price: { half: null, full: 40 },
    allergenAlert: "Wheat allergy",
    category: "meal",
    url: "http://Puri Subzi.....",
    quantity: 1,
  },
  {
    id: "product31",
    name: "Lassi",
    stock: true,
    price: "MRP",
    allergenAlert: "Milk allergy",
    category: "drink",
    url: "http://Honey Chilly Potatoes.....",
    quantity: 1,
  },
  {
    id: "product32",
    name: "Bottled Water",
    stock: true,
    price: { half: null, full: null },
    allergenAlert: "Rice allergy",
    category: "drink",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product33",
    name: "Chhole Bhature",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Wheat allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product34",
    name: "Tali (Rice, Roti, Subzi, Dal, Raita)",
    stock: true,
    price: { half: null, full: 60 },
    allergenAlert: "wheat allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product35",
    name: "Veg Chowmin",
    stock: true,
    price: { half: null, full: 40 },
    allergenAlert: "Wheat allergy",
    category: "snack",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product36",
    name: "Stuffed Paranth (with Achar)",
    stock: true,
    price: { half: null, full: 25 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product37",
    name: "Plain Dosa with Sambhar",
    stock: true,
    price: { half: null, full: 40 },
    allergenAlert: "Rice and lentils allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product38",
    name: "Masala Dosa with Sambhar",
    stock: true,
    price: { half: null, full: 45 },
    allergenAlert: "Rice and lentils allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product39",
    name: "Kachori with Subzi",
    stock: true,
    price: { half: null, full: 25 },
    allergenAlert: "Wheat allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product40",
    name: "Sambhar Vada)",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Wheat allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product41",
    name: "idli Sambhar",
    stock: true,
    price: { half: null, full: 35 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product42",
    name: "Uttapam",
    stock: true,
    price: { half: null, full: 50 },
    allergenAlert: "Rice allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product43",
    name: "Rasgulla",
    stock: true,
    price: { half: null, full: 20 },
    allergenAlert: "Rice allergy",
    category: "desert",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product44",
    name: "Ice Cream",
    stock: true,
    price: "MRP",
    allergenAlert: "Milk allergy",
    category: "desert",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
  {
    id: "product45",
    name: "Special Thali (4 Roti, Raita, Matar Paneer, Chawal, Subzi, Salad)",
    stock: true,
    price: { half: null, full: 80 },
    allergenAlert: "wheat allergy",
    category: "meal",
    url: "http://Rajma Rice.....",
    quantity: 1,
  },
];
