export const products = [
  {
    id: "product1",
    name: "Samosa",
    stock: true,
    price: 10,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Samosachutney.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product2",
    name: "Bread Pakoda",
    stock: true,
    price: 15,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/04/bread-pakora-recipe.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product3",
    name: "Bread Roll",
    stock: true,
    price: 10,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.shellyfoodspot.com/wp-content/uploads/2020/09/Indian-bread-roll-scaled-735x913.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product4",
    name: "Cream Roll",
    stock: true,
    price: 15,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://jahagirdarfoods.com/wp-content/uploads/2022/05/2-Cream-Roll-Vanilla-.png",
    quantity: 1,
    orders: {},
  },
  {
    id: "product5",
    name: "Sandwitch",
    stock: true,
    price: 25,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://thumbs.dreamstime.com/b/fresh-sandwitch-4446158.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product6",
    name: "Veg Burger",
    stock: true,
    price: 30,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-Vegetable-Deluxe-2:1-3-product-tile-desktop?wid=829&hei=515&dpr=off",
    quantity: 1,
    orders: {},
  },
  {
    id: "product7",
    name: "Veg Patty",
    stock: true,
    price: 15,
    ingredients: "wheat ",
    category: "Snack",
    url: "http://cdn.shopify.com/s/files/1/0279/6329/3831/products/Veg-Patty_grande.jpg?v=1578043022",
    quantity: 1,
    orders: {},
  },
  {
    id: "product8",
    name: "Veg cutlet",
    stock: true,
    price: 10,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/veg-cutlet-recipe.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product9",
    name: "Butter Slice",
    stock: true,
    price: 20,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.shutterstock.com/image-photo/stick-butter-cut-isolated-on-260nw-280511537.jpg",
    quantity: 2,
  },
  {
    id: "product10",
    name: "Double Egg Omellatee with two slice",
    stock: true,
    price: 40,
    ingredients: "Egg ",
    category: "Snack",
    url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/cheese-omelette-mozarella-omelette.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product11",
    name: "Spring Roll",
    stock: true,
    price: 60,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://productimages.withfloats.com/actual/624038417e882f0001e2fba6.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product12",
    name: "Momos",
    stock: true,
    price: 60,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.thespruceeats.com/thmb/UnVh_-znw7ikMUciZIx5sNqBtTU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/steamed-momos-wontons-1957616-hero-01-1c59e22bad0347daa8f0dfe12894bc3c.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product13",
    name: "Macroni",
    stock: true,
    price: 60,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://i.ytimg.com/vi/FH0JAl2Okpw/maxresdefault.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product14",
    name: "Pasta",
    stock: true,
    price: 60,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.sharmispassions.com/wp-content/uploads/2012/12/FusilliPasta8-500x375.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product15",
    name: "Chilly Patatoes",
    stock: true,
    price: 60,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://i0.wp.com/media.zeinaskitchen.se/2020/08/batata-harra-10.jpg?fit=1465%2C1500&ssl=1",
    quantity: 1,
    orders: {},
  },
  {
    id: "product16",
    name: "Poha",
    stock: true,
    price: 30,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://pipingpotcurry.com/wp-content/uploads/2020/12/Poha-Recipe-indori-Piping-Pot-Curry.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product17",
    name: "Vegetable Spring Roll",
    stock: true,
    price: 50,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.cilantroandcitronella.com/wp-content/uploads/2021/07/vegetable-spring-rolls-photo-735x1103.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product18",
    name: "Pav Bhaji",
    stock: true,
    price: 35,
    ingredients: "wheat ",
    category: "Snack",
    url: "https://www.cookwithmanali.com/wp-content/uploads/2018/05/Best-Pav-Bhaji-Recipe.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product19",
    name: "Tea",
    stock: true,
    price: 10,
    ingredients: "Milk ",
    category: "Drinks",
    url: "https://medicaldialogues.in/h-upload/2022/12/15/720x1280_193835-amp-background-image-91.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product20",
    name: "Coffee",
    stock: true,
    price: 15,
    ingredients: "Milk ",
    category: "Drinks",
    url: "https://images.indulgexpress.com/uploads/user/imagelibrary/2017/11/2/original/Cofeehouses.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product21",
    name: "Cold Drink",
    stock: true,
    price: null,
    ingredients: "Caffine ",
    category: "Drinks",
    url: "https://images.freekaamaal.com/post_images/1600942117.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product22",
    name: "Subzi",
    stock: true,
    price: 20,
    ingredients: "Vegetable ",
    category: "Meal",
    url: "https://www.pakistaneats.com/wp-content/uploads/2020/03/aloo-sabzi-angle-scaled.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product23",
    name: "Allu Bonda",
    stock: true,
    price: 10,
    ingredients: "Potatoes ",
    category: "Snack",
    url: "https://i0.wp.com/www.splashoftaste.com/wp-content/uploads/2022/04/Bonda-aloo-10-768x1024.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product24",
    name: "Honey Chilly Potatoes",
    stock: true,
    price: 70,
    ingredients: "Potatoes ",
    category: "Snack",
    url: "https://rakskitchen.net/wp-content/uploads/2022/07/honey-chilli.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product25",
    name: "Chhole Rice (with Subji, Salad)",
    stock: true,
    price: 35,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2021/02/Chole-with-cumin-rice-and-raita-b00cba7.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product26",
    name: "Rajma Rice",
    stock: true,
    price: 35,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://simplefreshnyum.com/wp-content/uploads/2021/10/Instant-pot-Rajma-ready-to-eat.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product27",
    name: "Dal Rice",
    stock: true,
    price: 35,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/nqq5izwrrgox7yaaagud",
    quantity: 1,
    orders: {},
  },
  {
    id: "product28",
    name: "chhole Rice",
    stock: true,
    price: 35,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://i.ytimg.com/vi/dQKeBJECYoI/maxresdefault.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product29",
    name: "Rajma Rice (with Subji)",
    stock: true,
    price: 40,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://i0.wp.com/www.sinamontales.com/dotcord/uploads/2016/06/of-sunday-afternoons-and-rajma-chawal.1024x1024-3.jpg?resize=1024%2C1541&ssl=1",
    quantity: 1,
    orders: {},
  },
  {
    id: "product30",
    name: "Puri Subzi",
    stock: true,
    price: 40,
    ingredients: "Wheat ",
    category: "Meal",
    url: "https://img.freepik.com/premium-photo/poori-masala-curry-aloo-sabzi-puri_466689-77508.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product31",
    name: "Lassi",
    stock: true,
    price: "MRP",
    ingredients: "Milk ",
    category: "Drinks",
    url: "https://static.toiimg.com/photo/58360232.cms",
    quantity: 1,
    orders: {},
  },
  {
    id: "product32",
    name: "Bottled Water",
    stock: true,
    price: null,
    ingredients: "Rice ",
    category: "Drinks",
    url: "https://www.bigbasket.com/media/uploads/p/xxl/103235-2_2-aquafina-packaged-drinking-water.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product33",
    name: "Chhole Bhature",
    stock: true,
    price: 35,
    ingredients: "Wheat ",
    category: "Meal",
    url: "https://en-media.thebetterindia.com/uploads/2022/08/294156779_1082267416022212_8006411537588067133_n-1_11zon-1660981126.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product34",
    name: "Tali (Rice, Roti, Subzi, Dal, Raita)",
    stock: true,
    price: 60,
    ingredients: "wheat ",
    category: "Meal",
    url: "https://www.archanaskitchen.com/images/archanaskitchen/6-WeeklyMealPlans/Meal_Plate_Carrot_Peanut_Salad_Tomato_Onion_Raita_phulka_Aloo_methi_pudina_chole_pindi-2.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product35",
    name: "Veg Chowmin",
    stock: true,
    price: 40,
    ingredients: "Wheat ",
    category: "Meal",
    url: "https://greenbowl2soul.com/wp-content/uploads/2019/11/vegetable-chow-mein.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product36",
    name: "Stuffed Paranth (with Achar)",
    stock: true,
    price: 25,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://static.toiimg.com/photo/53109843.cms",
    quantity: 1,
    orders: {},
  },
  {
    id: "product37",
    name: "Plain Dosa with Sambhar",
    stock: true,
    price: 40,
    ingredients: "Rice and lentils ",
    category: "Meal",
    url: "https://www.cookwithmanali.com/wp-content/uploads/2020/05/Masala-Dosa.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product38",
    name: "Masala Dosa with Sambhar",
    stock: true,
    price: 45,
    ingredients: "Rice and lentils ",
    category: "Meal",
    url: "https://ranveerbrar.com/wp-content/uploads/2021/02/Masala-dosa-scaled.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product39",
    name: "Kachori with Subzi",
    stock: true,
    price: 25,
    ingredients: "Wheat ",
    category: "Meal",
    url: "https://www.secondrecipe.com/wp-content/uploads/2020/03/kachori-aloo-sabji.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product40",
    name: "Sambhar Vada",
    stock: true,
    price: 35,
    ingredients: "Wheat ",
    category: "Meal",
    url: "https://i.ytimg.com/vi/V3RLMcOLYXQ/maxresdefault.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product41",
    name: "idli Sambhar",
    stock: true,
    price: 35,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://swadishtrecipes.in/wp-content/uploads/2023/01/Idli-Sambar-Recipe.png",
    quantity: 1,
    orders: {},
  },
  {
    id: "product42",
    name: "Uttapam",
    stock: true,
    price: 50,
    ingredients: "Rice ",
    category: "Meal",
    url: "https://cdn2.foodviva.com/static-content/food-images/south-indian-recipes/uttapam/uttapam.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product43",
    name: "Rasgulla",
    stock: true,
    price: 20,
    ingredients: "Rice ",
    category: "Sweets",
    url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2014/09/rasgulla-recipe-1-500x500.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product44",
    name: "Ice Cream",
    stock: true,
    price: "MRP",
    ingredients: "Milk ",
    category: "Meal",
    url: "https://jessicainthekitchen.com/wp-content/uploads/2022/03/Avocado-Ice-Cream6525.jpg",
    quantity: 1,
    orders: {},
  },
  {
    id: "product45",
    name: "Special Thali (4 Roti, Raita, Matar Paneer, Chawal, Subzi, Salad)",
    stock: true,
    price: 80,
    ingredients: "wheat ",
    category: "Meal",
    url: "https://b.zmtcdn.com/data/dish_photos/715/01f87d90ae534d082062ac6f9d5b0715.jpg",
    quantity: 1,
    orders: {},
  },
];
